### ISSUE TITLE
Question about FVQA

### ISSUE THREAD

**Issue by BackstreetK** [YuJungHeo/kbvqa-public#3]
Thanks for your sharing code.
But i have a question with the FVQA. 
Can you share the dataset and the config for FVQA?   Thanks.

**Comment by YuJungHeo** [comment]
Hello @BackstreetK,

Thank you for your interest in our work, and sorry for the late reply.
We just updated data, config, and pre-trained models for FVQA. 

Best Regards,
Yu-Jung
