### ISSUE TITLE
data process data

### ISSUE THREAD

**Issue by starry-y** [YuJungHeo/kbvqa-public#4]
Hi !
Thanks for your interesting work.
I have a question about data process.
Could you share code for processing data? 
Thank you very much.

**Comment by YuJungHeo** [comment]
Hello @starry-y,

Thank you for your interest in our work.
I have sent the preprocessing codes directly to your inbox.

If you have any questions or suggestions, feel free to contact me.

Best Regards,
Yu-Jung

**Comment by VTaPo** [comment]
Thank you for your wonderful research.
Could you share code for processing data?
Thank you very much!
