### ISSUE TITLE
About Linking to KB

### ISSUE THREAD

**Issue by VTaPo** [YuJungHeo/kbvqa-public#5]
Thank you for your wonderful research.
Can you walk me through how you link to the KB in your code?
It would be even better if you could suggest a reference to implement the pipeline from entity extraction to linking to KB and finally generating KGEs.
Thank you so much!

**Comment by VTaPo** [comment]
And I'm interested in the part from text to KB

**Comment by YuJungHeo** [comment]
Hello @VTaPo,

Thank you for your interest in our work. I have conducted exact matching of the nouns appearing in the question with the entities in the KB. If you provide your email, I can share the related preprocessing code with you.

Best Regards,
Yu-Jung

**Comment by VTaPo** [comment]
My email: ***@***.***
I would be very grateful to receive the data processing code as well as
resources related to entity linking.
I'm honestly so grateful for your help.

Thank you very much.
Phong

Vào Th 3, 20 thg 2, 2024 vào lúc 16:54 Yu-Jung Heo <
***@***.***> đã viết:

**Comment by YuJungHeo** [comment]
Hello @VTaPo,

I think your email address was masked due to GitHub's policy. Thus, I have attached the dropbox download link for preprocessing codes of the Hypergraph Transformer as follows: https://www.dropbox.com/scl/fi/cxcflsexwu10eegycrtmz/preprocessing_for_HGT.zip?rlkey=se90f0468b8dnf5qeu4bkqw7d&dl=0

Best Regards,
Yu-Jung

**Comment by VTaPo** [comment]
Thank you very much!
Phong

Vào Th 3, 20 thg 2, 2024 vào lúc 18:14 Yu-Jung Heo <
***@***.***> đã viết:

**Comment by VTaPo** [comment]
Hi, Sorry to bother you again.

I would like to ask if you know of any effective way to be able to map Qids
in KB to the real names of out world entities.
If there is a resource for that part hopefully you can share it with me.

Thanks a lot.
Phong

Vào Th 4, 21 thg 2, 2024 vào lúc 09:50 Phong Võ ***@***.***> đã
viết:
